name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/k-murakami0609/nesc/gstreamer
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get
        run: go get

      - name: Lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          reporter: github-pr-review

      - name: Test
        run: go test -v ./...
